apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authentication-operator-networkpolicy
  namespace: openshift-authentication-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  podSelector:
    matchLabels:
      app: authentication-operator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # allow metrics scraping from anywhere
  - ports:
    - protocol: TCP
      port: 8443
  egress:
  # allow egress to DNS
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
      podSelector:
        matchLabels:
          dns.operator.openshift.io/daemonset-dns: default
    ports:
    - protocol: TCP
      port: 5353
    - protocol: UDP
      port: 5353
  # allow egress traffic to oauth-server pods for health checks
  # this rule overlaps with the generic TCP egress rule but exists for documentation purposes
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-authentication
      podSelector:
        matchLabels:
          app: oauth-openshift
    ports:
    - protocol: TCP
      port: 6443
  # allow egress traffic to oauth-apiserver pods for health checks
  # this rule overlaps with the generic TCP egress rule but exists for documentation purposes
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-oauth-apiserver
      podSelector:
        matchLabels:
          app: openshift-oauth-apiserver
    ports:
    - protocol: TCP
      port: 8443
  # allow all egress traffic
  # required for egress to kube-apiserver pods and openID provider discovery (external OIDC and via oauth)
  - {}