# Expose operator metrics
apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: serving-cert
  labels:
    app: authentication-operator
  name: metrics
  namespace: openshift-authentication-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: authentication-operator
  sessionAffinity: None
  type: ClusterIP
