apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-authentication-operator
  name: authentication-operator-config
data:
  operator-config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
    servingInfo:
      bindNetwork: "tcp"
