apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-authentication-operator
  name: trusted-ca-bundle
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
