apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: authentication
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  - name: oauth-openshift
    version: "0.0.1-snapshot_openshift"
