apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-authentication-operator
  name: openshift-authentication-operator
  labels:
    app: origin-cluster-authentication-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: origin-cluster-authentication-operator
  template:
    metadata:
      name: origin-cluster-authentication-operator
      labels:
        app: origin-cluster-authentication-operator
    spec:
      serviceAccountName: openshift-authentication-operator
      containers:
      - name: operator
        image: quay.io/openshift/origin-cluster-authentication-operator:v4.0
        imagePullPolicy: Always
        command: ["authentication-operator", "operator"]
        args:
        - "--config=/var/run/configmaps/config/operator-config.yaml"
        - "-v=2"
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        env:
        - name: IMAGE
          value: quay.io/openshift/origin-hypershift:v4.0
        - name: OPERATOR_IMAGE
          value: docker.io/openshift/origin-cluster-authentication-operator:v4.0  # I believe this is supposed to exist
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: config
        configMap:
          defaultMode: 440
          name: openshift-authentication-operator-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: "system-cluster-critical"
      tolerations:
      - operator: Exists
