apiVersion: v1
data:
  audit.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    rules:
    - level: None
      nonResourceURLs:
      - "/healthz*"
      - "/logs"
      - "/metrics"
      - "/version"
    - level: Metadata
kind: ConfigMap
metadata:
  name: audit
  namespace: openshift-authentication
